services:
  app:
    build: .
    container_name: dongy-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      # CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      # CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      # JWT_SECRET: ${JWT_SECRET}
      # JWT_EXPIRES: ${JWT_EXPIRES}
      # UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      # UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
    command: sh -c "bunx prisma migrate deploy && bun run start"
    restart: unless-stopped
